# CMake generated Testfile for 
# Source directory: /home/ubuntu/ex_sharding
# Build directory: /home/ubuntu/ex_sharding
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gf-arithmetic")
subdirs("erasure-codes")
subdirs("lohi-generator")
subdirs("log-table-generator")
subdirs("libbloomfilter")
subdirs("libchannelserver")
subdirs("libdevcore")
subdirs("libdevcrypto")
subdirs("libethcore")
subdirs("evmc")
subdirs("libinterpreter")
subdirs("libevm")
subdirs("libtxpool")
subdirs("libstorage")
subdirs("libprecompiled")
subdirs("libnetwork")
subdirs("libp2p")
subdirs("libexecutive")
subdirs("libmptstate")
subdirs("libblockverifier")
subdirs("libstoragestate")
subdirs("libblockchain")
subdirs("libsync")
subdirs("libconsensus")
subdirs("libledger")
subdirs("librpc")
subdirs("libinitializer")
subdirs("libsecurity")
subdirs("libeventfilter")
