# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/ex_sharding

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/ex_sharding

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/ubuntu/ex_sharding/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/ex_sharding/CMakeFiles /home/ubuntu/ex_sharding/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/ex_sharding/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cryptopp

# Build rule for target.
cryptopp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptopp
.PHONY : cryptopp

# fast build rule for target.
cryptopp/fast:
	$(MAKE) -f CMakeFiles/cryptopp.dir/build.make CMakeFiles/cryptopp.dir/build
.PHONY : cryptopp/fast

#=============================================================================
# Target rules for targets named rocksdb

# Build rule for target.
rocksdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rocksdb
.PHONY : rocksdb

# fast build rule for target.
rocksdb/fast:
	$(MAKE) -f CMakeFiles/rocksdb.dir/build.make CMakeFiles/rocksdb.dir/build
.PHONY : rocksdb/fast

#=============================================================================
# Target rules for targets named leveldb

# Build rule for target.
leveldb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 leveldb
.PHONY : leveldb

# fast build rule for target.
leveldb/fast:
	$(MAKE) -f CMakeFiles/leveldb.dir/build.make CMakeFiles/leveldb.dir/build
.PHONY : leveldb/fast

#=============================================================================
# Target rules for targets named mhd

# Build rule for target.
mhd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mhd
.PHONY : mhd

# fast build rule for target.
mhd/fast:
	$(MAKE) -f CMakeFiles/mhd.dir/build.make CMakeFiles/mhd.dir/build
.PHONY : mhd/fast

#=============================================================================
# Target rules for targets named tbb

# Build rule for target.
tbb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tbb
.PHONY : tbb

# fast build rule for target.
tbb/fast:
	$(MAKE) -f CMakeFiles/tbb.dir/build.make CMakeFiles/tbb.dir/build
.PHONY : tbb/fast

#=============================================================================
# Target rules for targets named snappy

# Build rule for target.
snappy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snappy
.PHONY : snappy

# fast build rule for target.
snappy/fast:
	$(MAKE) -f CMakeFiles/snappy.dir/build.make CMakeFiles/snappy.dir/build
.PHONY : snappy/fast

#=============================================================================
# Target rules for targets named secp256k1

# Build rule for target.
secp256k1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 secp256k1
.PHONY : secp256k1

# fast build rule for target.
secp256k1/fast:
	$(MAKE) -f CMakeFiles/secp256k1.dir/build.make CMakeFiles/secp256k1.dir/build
.PHONY : secp256k1/fast

#=============================================================================
# Target rules for targets named mysqlclient

# Build rule for target.
mysqlclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlclient
.PHONY : mysqlclient

# fast build rule for target.
mysqlclient/fast:
	$(MAKE) -f CMakeFiles/mysqlclient.dir/build.make CMakeFiles/mysqlclient.dir/build
.PHONY : mysqlclient/fast

#=============================================================================
# Target rules for targets named jsonrpccpp

# Build rule for target.
jsonrpccpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsonrpccpp
.PHONY : jsonrpccpp

# fast build rule for target.
jsonrpccpp/fast:
	$(MAKE) -f CMakeFiles/jsonrpccpp.dir/build.make CMakeFiles/jsonrpccpp.dir/build
.PHONY : jsonrpccpp/fast

#=============================================================================
# Target rules for targets named boost

# Build rule for target.
boost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boost
.PHONY : boost

# fast build rule for target.
boost/fast:
	$(MAKE) -f CMakeFiles/boost.dir/build.make CMakeFiles/boost.dir/build
.PHONY : boost/fast

#=============================================================================
# Target rules for targets named libzdb

# Build rule for target.
libzdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libzdb
.PHONY : libzdb

# fast build rule for target.
libzdb/fast:
	$(MAKE) -f CMakeFiles/libzdb.dir/build.make CMakeFiles/libzdb.dir/build
.PHONY : libzdb/fast

#=============================================================================
# Target rules for targets named gperftools

# Build rule for target.
gperftools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gperftools
.PHONY : gperftools

# fast build rule for target.
gperftools/fast:
	$(MAKE) -f CMakeFiles/gperftools.dir/build.make CMakeFiles/gperftools.dir/build
.PHONY : gperftools/fast

#=============================================================================
# Target rules for targets named jsoncpp

# Build rule for target.
jsoncpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsoncpp
.PHONY : jsoncpp

# fast build rule for target.
jsoncpp/fast:
	$(MAKE) -f CMakeFiles/jsoncpp.dir/build.make CMakeFiles/jsoncpp.dir/build
.PHONY : jsoncpp/fast

#=============================================================================
# Target rules for targets named mini-p2p

# Build rule for target.
mini-p2p: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mini-p2p
.PHONY : mini-p2p

# fast build rule for target.
mini-p2p/fast:
	$(MAKE) -f CMakeFiles/mini-p2p.dir/build.make CMakeFiles/mini-p2p.dir/build
.PHONY : mini-p2p/fast

#=============================================================================
# Target rules for targets named gfarithmetic

# Build rule for target.
gfarithmetic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gfarithmetic
.PHONY : gfarithmetic

# fast build rule for target.
gfarithmetic/fast:
	$(MAKE) -f gf-arithmetic/CMakeFiles/gfarithmetic.dir/build.make gf-arithmetic/CMakeFiles/gfarithmetic.dir/build
.PHONY : gfarithmetic/fast

#=============================================================================
# Target rules for targets named log_tables

# Build rule for target.
log_tables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log_tables
.PHONY : log_tables

# fast build rule for target.
log_tables/fast:
	$(MAKE) -f gf-arithmetic/CMakeFiles/log_tables.dir/build.make gf-arithmetic/CMakeFiles/log_tables.dir/build
.PHONY : log_tables/fast

#=============================================================================
# Target rules for targets named encode-adv

# Build rule for target.
encode-adv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 encode-adv
.PHONY : encode-adv

# fast build rule for target.
encode-adv/fast:
	$(MAKE) -f gf-arithmetic/backends/CMakeFiles/encode-adv.dir/build.make gf-arithmetic/backends/CMakeFiles/encode-adv.dir/build
.PHONY : encode-adv/fast

#=============================================================================
# Target rules for targets named encode-ssse3

# Build rule for target.
encode-ssse3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 encode-ssse3
.PHONY : encode-ssse3

# fast build rule for target.
encode-ssse3/fast:
	$(MAKE) -f gf-arithmetic/backends/CMakeFiles/encode-ssse3.dir/build.make gf-arithmetic/backends/CMakeFiles/encode-ssse3.dir/build
.PHONY : encode-ssse3/fast

#=============================================================================
# Target rules for targets named encode-basic

# Build rule for target.
encode-basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 encode-basic
.PHONY : encode-basic

# fast build rule for target.
encode-basic/fast:
	$(MAKE) -f gf-arithmetic/backends/CMakeFiles/encode-basic.dir/build.make gf-arithmetic/backends/CMakeFiles/encode-basic.dir/build
.PHONY : encode-basic/fast

#=============================================================================
# Target rules for targets named encode-avx2

# Build rule for target.
encode-avx2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 encode-avx2
.PHONY : encode-avx2

# fast build rule for target.
encode-avx2/fast:
	$(MAKE) -f gf-arithmetic/backends/CMakeFiles/encode-avx2.dir/build.make gf-arithmetic/backends/CMakeFiles/encode-avx2.dir/build
.PHONY : encode-avx2/fast

#=============================================================================
# Target rules for targets named erasure

# Build rule for target.
erasure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 erasure
.PHONY : erasure

# fast build rule for target.
erasure/fast:
	$(MAKE) -f erasure-codes/CMakeFiles/erasure.dir/build.make erasure-codes/CMakeFiles/erasure.dir/build
.PHONY : erasure/fast

#=============================================================================
# Target rules for targets named generate-lohi-table

# Build rule for target.
generate-lohi-table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate-lohi-table
.PHONY : generate-lohi-table

# fast build rule for target.
generate-lohi-table/fast:
	$(MAKE) -f lohi-generator/CMakeFiles/generate-lohi-table.dir/build.make lohi-generator/CMakeFiles/generate-lohi-table.dir/build
.PHONY : generate-lohi-table/fast

#=============================================================================
# Target rules for targets named generate-log-tables

# Build rule for target.
generate-log-tables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate-log-tables
.PHONY : generate-log-tables

# fast build rule for target.
generate-log-tables/fast:
	$(MAKE) -f log-table-generator/CMakeFiles/generate-log-tables.dir/build.make log-table-generator/CMakeFiles/generate-log-tables.dir/build
.PHONY : generate-log-tables/fast

#=============================================================================
# Target rules for targets named libbf_static

# Build rule for target.
libbf_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libbf_static
.PHONY : libbf_static

# fast build rule for target.
libbf_static/fast:
	$(MAKE) -f libbloomfilter/CMakeFiles/libbf_static.dir/build.make libbloomfilter/CMakeFiles/libbf_static.dir/build
.PHONY : libbf_static/fast

#=============================================================================
# Target rules for targets named channelserver

# Build rule for target.
channelserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 channelserver
.PHONY : channelserver

# fast build rule for target.
channelserver/fast:
	$(MAKE) -f libchannelserver/CMakeFiles/channelserver.dir/build.make libchannelserver/CMakeFiles/channelserver.dir/build
.PHONY : channelserver/fast

#=============================================================================
# Target rules for targets named devcore

# Build rule for target.
devcore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 devcore
.PHONY : devcore

# fast build rule for target.
devcore/fast:
	$(MAKE) -f libdevcore/CMakeFiles/devcore.dir/build.make libdevcore/CMakeFiles/devcore.dir/build
.PHONY : devcore/fast

#=============================================================================
# Target rules for targets named devcrypto

# Build rule for target.
devcrypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 devcrypto
.PHONY : devcrypto

# fast build rule for target.
devcrypto/fast:
	$(MAKE) -f libdevcrypto/CMakeFiles/devcrypto.dir/build.make libdevcrypto/CMakeFiles/devcrypto.dir/build
.PHONY : devcrypto/fast

#=============================================================================
# Target rules for targets named ethcore

# Build rule for target.
ethcore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ethcore
.PHONY : ethcore

# fast build rule for target.
ethcore/fast:
	$(MAKE) -f libethcore/CMakeFiles/ethcore.dir/build.make libethcore/CMakeFiles/ethcore.dir/build
.PHONY : ethcore/fast

#=============================================================================
# Target rules for targets named instructions

# Build rule for target.
instructions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 instructions
.PHONY : instructions

# fast build rule for target.
instructions/fast:
	$(MAKE) -f evmc/lib/instructions/CMakeFiles/instructions.dir/build.make evmc/lib/instructions/CMakeFiles/instructions.dir/build
.PHONY : instructions/fast

#=============================================================================
# Target rules for targets named loader

# Build rule for target.
loader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 loader
.PHONY : loader

# fast build rule for target.
loader/fast:
	$(MAKE) -f evmc/lib/loader/CMakeFiles/loader.dir/build.make evmc/lib/loader/CMakeFiles/loader.dir/build
.PHONY : loader/fast

#=============================================================================
# Target rules for targets named interpreter

# Build rule for target.
interpreter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interpreter
.PHONY : interpreter

# fast build rule for target.
interpreter/fast:
	$(MAKE) -f libinterpreter/CMakeFiles/interpreter.dir/build.make libinterpreter/CMakeFiles/interpreter.dir/build
.PHONY : interpreter/fast

#=============================================================================
# Target rules for targets named evm

# Build rule for target.
evm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evm
.PHONY : evm

# fast build rule for target.
evm/fast:
	$(MAKE) -f libevm/CMakeFiles/evm.dir/build.make libevm/CMakeFiles/evm.dir/build
.PHONY : evm/fast

#=============================================================================
# Target rules for targets named txpool

# Build rule for target.
txpool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 txpool
.PHONY : txpool

# fast build rule for target.
txpool/fast:
	$(MAKE) -f libtxpool/CMakeFiles/txpool.dir/build.make libtxpool/CMakeFiles/txpool.dir/build
.PHONY : txpool/fast

#=============================================================================
# Target rules for targets named storage

# Build rule for target.
storage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storage
.PHONY : storage

# fast build rule for target.
storage/fast:
	$(MAKE) -f libstorage/CMakeFiles/storage.dir/build.make libstorage/CMakeFiles/storage.dir/build
.PHONY : storage/fast

#=============================================================================
# Target rules for targets named precompiled

# Build rule for target.
precompiled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 precompiled
.PHONY : precompiled

# fast build rule for target.
precompiled/fast:
	$(MAKE) -f libprecompiled/CMakeFiles/precompiled.dir/build.make libprecompiled/CMakeFiles/precompiled.dir/build
.PHONY : precompiled/fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network
.PHONY : network

# fast build rule for target.
network/fast:
	$(MAKE) -f libnetwork/CMakeFiles/network.dir/build.make libnetwork/CMakeFiles/network.dir/build
.PHONY : network/fast

#=============================================================================
# Target rules for targets named p2p

# Build rule for target.
p2p: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p2p
.PHONY : p2p

# fast build rule for target.
p2p/fast:
	$(MAKE) -f libp2p/CMakeFiles/p2p.dir/build.make libp2p/CMakeFiles/p2p.dir/build
.PHONY : p2p/fast

#=============================================================================
# Target rules for targets named executivecontext

# Build rule for target.
executivecontext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executivecontext
.PHONY : executivecontext

# fast build rule for target.
executivecontext/fast:
	$(MAKE) -f libexecutive/CMakeFiles/executivecontext.dir/build.make libexecutive/CMakeFiles/executivecontext.dir/build
.PHONY : executivecontext/fast

#=============================================================================
# Target rules for targets named mptstate

# Build rule for target.
mptstate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mptstate
.PHONY : mptstate

# fast build rule for target.
mptstate/fast:
	$(MAKE) -f libmptstate/CMakeFiles/mptstate.dir/build.make libmptstate/CMakeFiles/mptstate.dir/build
.PHONY : mptstate/fast

#=============================================================================
# Target rules for targets named blockverifier

# Build rule for target.
blockverifier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockverifier
.PHONY : blockverifier

# fast build rule for target.
blockverifier/fast:
	$(MAKE) -f libblockverifier/CMakeFiles/blockverifier.dir/build.make libblockverifier/CMakeFiles/blockverifier.dir/build
.PHONY : blockverifier/fast

#=============================================================================
# Target rules for targets named storagestate

# Build rule for target.
storagestate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storagestate
.PHONY : storagestate

# fast build rule for target.
storagestate/fast:
	$(MAKE) -f libstoragestate/CMakeFiles/storagestate.dir/build.make libstoragestate/CMakeFiles/storagestate.dir/build
.PHONY : storagestate/fast

#=============================================================================
# Target rules for targets named blockchain

# Build rule for target.
blockchain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain
.PHONY : blockchain

# fast build rule for target.
blockchain/fast:
	$(MAKE) -f libblockchain/CMakeFiles/blockchain.dir/build.make libblockchain/CMakeFiles/blockchain.dir/build
.PHONY : blockchain/fast

#=============================================================================
# Target rules for targets named sync

# Build rule for target.
sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sync
.PHONY : sync

# fast build rule for target.
sync/fast:
	$(MAKE) -f libsync/CMakeFiles/sync.dir/build.make libsync/CMakeFiles/sync.dir/build
.PHONY : sync/fast

#=============================================================================
# Target rules for targets named consensus

# Build rule for target.
consensus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 consensus
.PHONY : consensus

# fast build rule for target.
consensus/fast:
	$(MAKE) -f libconsensus/CMakeFiles/consensus.dir/build.make libconsensus/CMakeFiles/consensus.dir/build
.PHONY : consensus/fast

#=============================================================================
# Target rules for targets named ledger

# Build rule for target.
ledger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ledger
.PHONY : ledger

# fast build rule for target.
ledger/fast:
	$(MAKE) -f libledger/CMakeFiles/ledger.dir/build.make libledger/CMakeFiles/ledger.dir/build
.PHONY : ledger/fast

#=============================================================================
# Target rules for targets named rpc

# Build rule for target.
rpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpc
.PHONY : rpc

# fast build rule for target.
rpc/fast:
	$(MAKE) -f librpc/CMakeFiles/rpc.dir/build.make librpc/CMakeFiles/rpc.dir/build
.PHONY : rpc/fast

#=============================================================================
# Target rules for targets named initializer

# Build rule for target.
initializer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 initializer
.PHONY : initializer

# fast build rule for target.
initializer/fast:
	$(MAKE) -f libinitializer/CMakeFiles/initializer.dir/build.make libinitializer/CMakeFiles/initializer.dir/build
.PHONY : initializer/fast

#=============================================================================
# Target rules for targets named security

# Build rule for target.
security: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 security
.PHONY : security

# fast build rule for target.
security/fast:
	$(MAKE) -f libsecurity/CMakeFiles/security.dir/build.make libsecurity/CMakeFiles/security.dir/build
.PHONY : security/fast

#=============================================================================
# Target rules for targets named eventfilter

# Build rule for target.
eventfilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eventfilter
.PHONY : eventfilter

# fast build rule for target.
eventfilter/fast:
	$(MAKE) -f libeventfilter/CMakeFiles/eventfilter.dir/build.make libeventfilter/CMakeFiles/eventfilter.dir/build
.PHONY : eventfilter/fast

Client.o: Client.cpp.o

.PHONY : Client.o

# target to build an object file
Client.cpp.o:
	$(MAKE) -f CMakeFiles/mini-p2p.dir/build.make CMakeFiles/mini-p2p.dir/Client.cpp.o
.PHONY : Client.cpp.o

Client.i: Client.cpp.i

.PHONY : Client.i

# target to preprocess a source file
Client.cpp.i:
	$(MAKE) -f CMakeFiles/mini-p2p.dir/build.make CMakeFiles/mini-p2p.dir/Client.cpp.i
.PHONY : Client.cpp.i

Client.s: Client.cpp.s

.PHONY : Client.s

# target to generate assembly for a file
Client.cpp.s:
	$(MAKE) -f CMakeFiles/mini-p2p.dir/build.make CMakeFiles/mini-p2p.dir/Client.cpp.s
.PHONY : Client.cpp.s

p2p_main.o: p2p_main.cpp.o

.PHONY : p2p_main.o

# target to build an object file
p2p_main.cpp.o:
	$(MAKE) -f CMakeFiles/mini-p2p.dir/build.make CMakeFiles/mini-p2p.dir/p2p_main.cpp.o
.PHONY : p2p_main.cpp.o

p2p_main.i: p2p_main.cpp.i

.PHONY : p2p_main.i

# target to preprocess a source file
p2p_main.cpp.i:
	$(MAKE) -f CMakeFiles/mini-p2p.dir/build.make CMakeFiles/mini-p2p.dir/p2p_main.cpp.i
.PHONY : p2p_main.cpp.i

p2p_main.s: p2p_main.cpp.s

.PHONY : p2p_main.s

# target to generate assembly for a file
p2p_main.cpp.s:
	$(MAKE) -f CMakeFiles/mini-p2p.dir/build.make CMakeFiles/mini-p2p.dir/p2p_main.cpp.s
.PHONY : p2p_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cryptopp"
	@echo "... rocksdb"
	@echo "... leveldb"
	@echo "... mhd"
	@echo "... install"
	@echo "... tbb"
	@echo "... snappy"
	@echo "... secp256k1"
	@echo "... test"
	@echo "... mysqlclient"
	@echo "... jsonrpccpp"
	@echo "... boost"
	@echo "... libzdb"
	@echo "... gperftools"
	@echo "... package"
	@echo "... install/strip"
	@echo "... jsoncpp"
	@echo "... mini-p2p"
	@echo "... package_source"
	@echo "... gfarithmetic"
	@echo "... log_tables"
	@echo "... encode-adv"
	@echo "... encode-ssse3"
	@echo "... encode-basic"
	@echo "... encode-avx2"
	@echo "... erasure"
	@echo "... generate-lohi-table"
	@echo "... generate-log-tables"
	@echo "... libbf_static"
	@echo "... channelserver"
	@echo "... devcore"
	@echo "... devcrypto"
	@echo "... ethcore"
	@echo "... instructions"
	@echo "... loader"
	@echo "... interpreter"
	@echo "... evm"
	@echo "... txpool"
	@echo "... storage"
	@echo "... precompiled"
	@echo "... network"
	@echo "... p2p"
	@echo "... executivecontext"
	@echo "... mptstate"
	@echo "... blockverifier"
	@echo "... storagestate"
	@echo "... blockchain"
	@echo "... sync"
	@echo "... consensus"
	@echo "... ledger"
	@echo "... rpc"
	@echo "... initializer"
	@echo "... security"
	@echo "... eventfilter"
	@echo "... Client.o"
	@echo "... Client.i"
	@echo "... Client.s"
	@echo "... p2p_main.o"
	@echo "... p2p_main.i"
	@echo "... p2p_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

